plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

application {
    mainClass = 'com.citadel.tictactoe.core.TicTacToeApp'
}

javafx {
    version = '21'
    modules = ['javafx.controls']
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'org.xerial:sqlite-jdbc:3.53.2.0'
    testImplementation 'junit:junit:4.13.1'
}

test {
    useJUnitPlatform()
    useJUnit()
    testLogging.showStandardStreams = true
}