@startuml
class main.models.modules.game.Coordinate {
+ {static} int DIMENSION = 3
# int getDimension()
+ String toString()
+ int hashCode()
+ boolean equals(Object)
}


main.models.coordinate.SquareBoundedCoordinate <|-- main.models.modules.game.Coordinate

@enduml