@startuml secuencia-repeticion
actor Jugador
participant ReplayModule
participant LocalSelectReplayController
participant SelectReplayView
participant LocalReplayLogic
participant ReplayController
participant ConsoleReplayView

Jugador -> ReplayModule : selecciona "Repetir partida"
ReplayModule -> LocalSelectReplayController : new(gameHistoryRegistry)
ReplayModule -> SelectReplayView : interact(controller)
Jugador -> SelectReplayView : elige partida
ReplayModule -> LocalSelectReplayController : getSelected()
LocalSelectReplayController --> ReplayModule : MoveHistory

ReplayModule -> LocalReplayLogic : new LocalReplayLogic(history)
loop mientras controller != null
  ReplayModule -> LocalReplayLogic : getController()
  LocalReplayLogic --> ReplayModule : ReplayController
  ReplayModule -> ConsoleReplayView : interact(controller)
  ConsoleReplayView -> ReplayController : accept(this)
  ConsoleReplayView -> ReplayController : getPosition() / getTotal() / getColor(...)
  Jugador -> ConsoleReplayView : elige Siguiente/Anterior/Salir
  ConsoleReplayView -> ReplayController : next() / previous() / exit()
end
@enduml
